language: node_js
node_js:
  - "stable"
services:
  - docker
before_install:
  - docker build -t weather-app-image -f Dockerfile.dev .
script:
  - docker run -e CI=true weather-app-image npm run test -- --coverage
on:
  branch: master