sudo: required
services:
  - docker
before_install:
  - docker build -t weather-app-image -f Dockerfile.dev .
script:
  - docker run -e CI=true weather-app-image npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "weather-react-docker-app"
  env: "WeatherReactDockerApp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-052894633894"
  bucket_path: "weather-react-docker-app"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY